function wngui()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load wngui                             

a = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'PointerShapeCData',mat1, ...
	'Position',[410 116 561 352], ...
	'Resize','off', ...
	'Tag','StaffWindow');
b = uicontrol('Parent',a, ...
	'Units','points', ...
	'BackgroundColor',[0.752941 0.752941 0.752941], ...
	'Callback',mat2, ...
	'Max',74, ...
	'Position',[126 12 168.75 14.25], ...
	'Style','slider', ...
	'Tag','StaffScroll', ...
	'Value',4.144);
b = axes('Parent',a, ...
	'Units','points', ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',mat3, ...
	'NextPlot','add', ...
	'Position',[41.25 53.25 337.5 183.75], ...
	'Tag','StaffAxes', ...
	'XColor',[1 1 1], ...
	'XLim',[0 52], ...
	'XLimMode','manual', ...
	'XTickLabel',mat4, ...
	'XTickLabelMode','manual', ...
	'XTickMode','manual', ...
	'YColor',[1 1 1], ...
	'YLim',[0 32], ...
	'YLimMode','manual', ...
	'YTickMode','manual', ...
	'ZColor',[0 0 0]);
c = text('Parent',b, ...
	'Color',[1 1 1], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[25.9421 -1.04918 0], ...
	'Tag','Axes1Text4', ...
	'VerticalAlignment','cap');
set(get(c,'Parent'),'XLabel',c);
c = text('Parent',b, ...
	'Color',[1 1 1], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.81069 15.8689 0], ...
	'Rotation',90, ...
	'Tag','Axes1Text3', ...
	'VerticalAlignment','baseline');
set(get(c,'Parent'),'YLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','right', ...
	'Position',[-6.48552 36.5902 0], ...
	'Tag','Axes1Text2', ...
	'Visible','off');
set(get(c,'Parent'),'ZLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[25.9421 32.918 0], ...
	'Tag','Axes1Text1', ...
	'VerticalAlignment','bottom');
set(get(c,'Parent'),'Title',c);
