function  musicg_x()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load musicg_x                         

scr_units = get(0,'units');
scr_siz = get(0,'screensize');
win_pos = [460 120 486 532];
if( (win_pos(1)+win_pos(3))>scr_siz(3) )
   win_pos(1) = max([0,round(scr_siz(3)/2 - win_pos(3)/2)]);
end
if( (win_pos(2)+win_pos(4))>scr_siz(4) )
   win_pos(2) = max([0,round(scr_siz(4)/2 - win_pos(4)/2)]);
end
%win_pos;
set(0,'units',scr_units);

a = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'Position',win_pos, ...
	'Tag','Fig1');
b = uimenu('Parent',a, ...
	'Label','Demos', ...
	'Tag','DemoMenu');
c = uimenu('Parent',b, ...
	'Callback',mat1, ...
	'Label','C-Major Scale', ...
	'Tag','cmajor');
c = uimenu('Parent',b, ...
	'Callback',mat2, ...
	'Label','C-Minor Scale', ...
	'Tag','cminor');
c = uimenu('Parent',b, ...
	'Callback',mat3, ...
	'Label','Beethoven''s Fifth', ...
	'Tag','Beet5');
c = uimenu('Parent',b, ...
	'Callback',mat4, ...
	'Label','Bach''s Minuet in G', ...
	'Tag','MinuetG');
c = uimenu('Parent',b, ...
	'Callback',mat5, ...
	'Label','Jesu, Joy of Man''s Desiring', ...
	'Tag','Jesu');
b = uimenu('Parent',a, ...
	'Label','HowTo', ...
	'Tag','HowTo');
c = uimenu('Parent',b, ...
	'Callback','helptext', ...
	'Label','How To Use MusicLab', ...
	'Tag','HowToUse');
c = uimenu('Parent',b, ...
	'Callback','staffmap', ...
	'Label','Staff Note Map', ...
	'Tag','StaffMap');
c = uimenu('Parent',b, ...
	'Callback','keymap', ...
	'Label','Key Note Map', ...
	'Tag','KeyMap');
c = uimenu('Parent',b, ...
	'Callback','keynums', ...
	'Label','Key Number Map', ...
	'Tag','KeyNumMap');
c = uimenu('Parent',b, ...
	'Callback','mg_notab', ...
	'Label','Note Duration Diagram', ...
	'Tag','NoteDurDiagram');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[0.135379 0.834586 0.350181 0.04], ...
	'Style','edit', ...
	'Tag','NoteEntry');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[0.521661 0.834586 0.350181 0.04], ...
	'Style','edit', ...
	'Tag','DurEntry');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[0.126354 0.88 0.326715 0.0300752], ...
	'String','Enter a melody:', ...
	'Style','text', ...
	'Tag','NoteText');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[0.521661 0.88 0.326715 0.0300752], ...
	'String','Enter the note durations:', ...
	'Style','text', ...
	'Tag','DurText');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',18, ...
	'Position',[0.176895 0.921365 0.651625 0.0578635], ...
	'String','Music Spectrogram Lab', ...
	'Style','text', ...
	'Tag','Heading');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'Callback',mat6, ...
	'Position',[0.453069 0.0112782 0.198556 0.0545113], ...
	'String','Back to Beginning', ...
	'Tag','Begin');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'Callback',mat7, ...
	'Position',[0.0974729 0.0112782 0.135379 0.0545113], ...
	'String','>>', ...
	'Tag','Forward');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'Callback',mat8, ...
	'Position',[0.763538 0.0112782 0.135379 0.0545113], ...
	'String','Clear', ...
	'Tag','Clear');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'Callback',mat9, ...
	'Position',[0.274368 0.0112782 0.135379 0.0545113], ...
	'String','<<', ...
	'Tag','Back');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'Callback',mat10, ...
	'Position',[0.34296 0.757519 0.3213 0.0507519], ...
	'String','Apply', ...
	'Tag','Apply');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'Callback',mat11, ...
	'Position',[0.108303 0.757519 0.211191 0.0507519], ...
	'String','Add Harmony', ...
	'Tag','AddHarmony');
b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.733333 0.733333 0.733333], ...
	'Callback','soundsc(song,8000);', ...
	'Position',[0.687726 0.757519 0.211191 0.0507519], ...
	'String','Play Song', ...
	'Tag','PlaySong');
b = axes('Parent',a, ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',mat12, ...
	'CreateFcn','cla', ...
	'NextPlot','add', ...
	'Position',[0.1893 0.428571 0.713992 0.296992], ...
	'Tag','Staff', ...
	'XColor',[1 1 1], ...
	'XLim',[0 52], ...
	'XLimMode','manual', ...
	'XTickMode','manual', ...
	'YColor',[1 1 1], ...
	'YLim',[0 32], ...
	'YLimMode','manual', ...
	'YTickMode','manual', ...
	'ZColor',[0 0 0]);
c = text('Parent',b, ...
	'Color',[1 1 1], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[25.8497 -1.63057 0], ...
	'Tag','Text1', ...
	'VerticalAlignment','cap');
set(get(c,'Parent'),'XLabel',c);
c = text('Parent',b, ...
	'Color',[1 1 1], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[-1.05202 15.6943 0], ...
	'Rotation',90, ...
	'Tag','Text2', ...
	'VerticalAlignment','baseline');
set(get(c,'Parent'),'YLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','right', ...
	'Position',[-13.8266 61.5541 0], ...
	'Tag','Text3', ...
	'Visible','off');
set(get(c,'Parent'),'ZLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[25.8497 33.4268 0], ...
	'Tag','Text4', ...
	'VerticalAlignment','bottom');
set(get(c,'Parent'),'Title',c);
b = axes('Parent',a, ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',mat13, ...
	'NextPlot','add', ...
	'Position',[0.0946502 0.428571 0.0967078 0.296992], ...
	'Tag','Clefs', ...
	'XColor',[1 1 1], ...
	'XLim',[1 8], ...
	'XLimMode','manual', ...
	'XTickLabel',['0  ';'0.5';'1  '], ...
	'XTickLabelMode','manual', ...
	'XTickMode','manual', ...
	'YColor',[1 1 1], ...
	'YLim',[0 32], ...
	'YLimMode','manual', ...
	'YTickMode','manual', ...
	'ZColor',[0 0 0]);
c = text('Parent',b, ...
	'Color',[1 1 1], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[4.34783 -1.63057 0], ...
	'Tag','Text9', ...
	'VerticalAlignment','cap');
set(get(c,'Parent'),'XLabel',c);
c = text('Parent',b, ...
	'Color',[1 1 1], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.0652174 15.6943 0], ...
	'Rotation',90, ...
	'Tag','Text10', ...
	'VerticalAlignment','baseline');
set(get(c,'Parent'),'YLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','right', ...
	'Position',[-6 61.5541 0], ...
	'Tag','Text11', ...
	'Visible','off');
set(get(c,'Parent'),'ZLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[4.34783 33.4268 0], ...
	'Tag','Text12', ...
	'VerticalAlignment','bottom');
set(get(c,'Parent'),'Title',c);
b = axes('Parent',a, ...
	'AmbientLightColor',[0.4 0.7 1], ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'CLim',[0 65.7047], ...
	'CLimMode','manual', ...
	'Color',[0 0 0.6], ...
	'ColorOrder',mat14, ...
	'CreateFcn','cla', ...
	'GridLineStyle','none', ...
	'NextPlot','add', ...
	'Position',[0.101083 0.148496 0.799639 0.25188], ...
	'Tag','Spec', ...
	'XColor',[0 0 0], ...
	'XGrid','on', ...
	'XLim',[0 7.5], ...
	'XLimMode','manual', ...
	'XTick',mat15, ...
	'XTickMode','manual', ...
	'YColor',[0 0 0], ...
	'YGrid','on', ...
	'YLim',[0 1000], ...
	'YLimMode','manual', ...
	'YTick',[0 200 400 600 800 1000], ...
	'YTickMode','manual', ...
	'ZColor',[0 0 0], ...
	'ZGrid','on');
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[3.74031 -179.104 0], ...
	'String','Time', ...
	'Tag','Text5', ...
	'VerticalAlignment','cap');
set(get(c,'Parent'),'XLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[-0.755814 492.537 0], ...
	'Rotation',90, ...
	'String','Frequency', ...
	'Tag','Text6', ...
	'VerticalAlignment','baseline');
set(get(c,'Parent'),'YLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','right', ...
	'Position',[-0.968992 3365.67 0], ...
	'Tag','Text7', ...
	'Visible','off');
set(get(c,'Parent'),'ZLabel',c);
c = text('Parent',b, ...
	'Color',[0 0 0], ...
	'HandleVisibility','callback', ...
	'HorizontalAlignment','center', ...
	'Position',[3.74031 1052.24 0], ...
	'Tag','Text8', ...
	'VerticalAlignment','bottom');
set(get(c,'Parent'),'Title',c);
